"""Source-derived round-three report and next-fit inventory."""
import hashlib
import run_cjh_feed_ratio_01 as b
C=b.ROOT/'docs/research/rph-yield-grid-2026-09-07';D=C/'bo-03'
p=b.read(D/'proposal.json');gate=b.read(D/'verification/gates.json');status=b.read(D/'verify-run.json')
assert status['status']=='completed' and gate['phase_error']<gate['threshold']
source=D/'verification/n800.json';raw=b.read(source)
rows=b.read(D/'training.json')['rows'].copy()
rows.append(dict(peak_C=p['peak_C'],hold_s=p['hold_s'],flow_sccm=p['flow_sccm'],C2H2_Y_pct=gate['actual_Y_pct'],source=str(source.relative_to(b.ROOT)),sha256=hashlib.sha256(source.read_bytes()).hexdigest(),solver_rtol=raw['solver_rtol'],selection_class='EI'))
assert len(rows)==72
b.write(D/'observations-for-next-fit.json',dict(rows=rows,n=72,fitted=False))
summary=dict(proposal=p,actual_Y_pct=gate['actual_Y_pct'],improvement_pp=gate['actual_Y_pct']-p['incumbent_Y_pct'],phase_error=gate['phase_error'],cycles=raw['cycles'],fit_wall_s=b.read(D/'propose-run.json')['wall_s'],verification_wall_s=status['wall_s'],spent_s=b.read(C/'budget.json')['spent_s'])
b.write(D/'report.json',summary)
(D/'REPORT.md').write_text(f"""# Third EI recommendation after exploration

The 71-point NEXTorch GP selects {p['peak_C']:.5f} °C, {p['hold_s']:.2f} s hot hold and {p['flow_sccm']:.2f} sccm using EI. This is not one of the separately selected exploration points. The domain and reactor closures remain unchanged.

Predicted acetylene carbon yield: {p['predicted_Y_pct'][0]:.6f}% with posterior SD {p['posterior_sd_pp'][0]:.6f} percentage points. Verified yield: {gate['actual_Y_pct']:.6f}%. Difference from prior best: {summary['improvement_pp']:.6f} percentage points. The candidate does not improve the incumbent.

Paired phase error: {gate['phase_error']:.9g}, below {gate['threshold']}. Periodic convergence occurs at cycle {raw['cycles']}; the worker's other temperature, pressure and balance gates pass. Relative tolerance remains 1e-11. Fit/search: {summary['fit_wall_s']:.3f} s. Verification: {status['wall_s']:.3f} s. All elapsed stages are recorded in the existing ledger.

Accept this observation for the next model. The next-fit inventory contains 72 observations; the fitted GP remains at 71. The exploration warning is retained. Three EI results and two exploration results do not establish global convergence, a boundary optimum or an advantage over another search strategy. No fourth EI proposal was generated.

Source: Actions run 34180903364, paired outputs and manifest in verification/. report.json and this report are generated by tools/openmkm_dynamic/report_rph_bo03.py.
""")
print(summary)
