"""Summarize sequential sampling gains without claiming predictive validation."""
import argparse
import json
from pathlib import Path


def progress(summaries):
    rows, seen, history = [], set(), []
    previous = {k: None for k in ("C2H2_carbon_yield", "C2H4_carbon_yield")}
    for label, batch in summaries:
        for row in batch:
            key = (row["T_C"], row["tau_s"], row["mechanism"])
            if key in seen:
                raise ValueError("duplicate sampled condition")
            seen.add(key)
            rows.append(row)
        maxima = {}
        for key in previous:
            best = max(rows, key=lambda r: r[key])
            maxima[key] = dict(T_C=best["T_C"], tau_s=best["tau_s"], value=best[key],
                gain_percentage_points=None if previous[key] is None else 100*(best[key]-previous[key]))
            previous[key] = best[key]
        history.append(dict(source=label, cumulative_points=len(rows), maxima=maxima))
    return history


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--summaries", type=Path, nargs="+", required=True)
    ap.add_argument("--output-dir", type=Path, required=True)
    a = ap.parse_args()
    history = progress([(str(p), json.loads(p.read_text())) for p in a.summaries])
    a.output_dir.mkdir(parents=True, exist_ok=True)
    (a.output_dir/"sampling-progress.json").write_text(json.dumps(history, indent=2)+"\n")
    lines = ["# Sequential CJH sampling gains", "",
        "Generated by tools/openmkm_dynamic/summarize_cjh_progress.py from archived summaries.",
        "Carbon yields use total inlet carbon. This is not a predictive learning curve or global-optimum certificate.", "",
        "| Points | Best C2H2 % | Gain, percentage points | Best C2H4 % | Gain, percentage points |",
        "|---|---|---|---|---|"]
    for step in history:
        values = [str(step["cumulative_points"])]
        for key in ("C2H2_carbon_yield", "C2H4_carbon_yield"):
            m = step["maxima"][key]
            values += [f"{100*m['value']:.6f}", "n/a" if m["gain_percentage_points"] is None else f"{m['gain_percentage_points']:.6f}"]
        lines.append("| "+" | ".join(values)+" |")
    lines += ["", "Diminishing improvement supports pausing this targeted extension, not concluding that all unsampled regions are resolved.",
        "Next priority: independently test integrator tolerances and alternate initial compositions at representative candidates.",
        "Published mechanism accuracy, soot omission, reactor mixing and heater-energy feasibility remain separate limitations."]
    (a.output_dir/"SAMPLING-PROGRESS.md").write_text("\n".join(lines)+"\n")


if __name__ == "__main__":
    main()
