"""Deterministic CJH table and sampled Pareto plot; no interpolated optima."""
import argparse
import json
from pathlib import Path


def nondominated(rows):
    keys = ("C2H2_carbon_yield", "CO_carbon_yield")
    return [r for r in rows if not any(
        all(s[k] >= r[k] for k in keys) and any(s[k] > r[k] for k in keys)
        for s in rows)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--summaries", nargs="+", type=Path, required=True)
    ap.add_argument("--output-dir", type=Path, required=True)
    ap.add_argument("--feed", default="CH4/CO2=50/50",
                    help="stated in the header; the acetic-acid ceiling is a "
                         "CH4-plus-CO2 combination bound and is reported only "
                         "for a feed that carries CO2")
    a = ap.parse_args()
    aa = "CO2" in a.feed
    unique = {}
    for file in a.summaries:
        for r in json.loads(file.read_text()):
            key = (r["T_C"], r["tau_s"], r["mechanism"])
            assert key not in unique, "duplicate point needs explicit reconciliation"
            unique[key] = r
    rows = sorted(unique.values(), key=lambda r: (r["T_C"], r["tau_s"]))
    front = nondominated(rows)
    out = a.output_dir
    out.mkdir(parents=True, exist_ok=True)
    lines = ["# Aramco CJH sampled map", "",
        f"Generated by tools/openmkm_dynamic/summarize_cjh_map.py. {a.feed}, 1 atm.",
        "Prescribed constant gas temperature, homogeneous CSTR; no heater-energy or device validation.",
        "Carbon yields use total inlet carbon." + (
            " AA is a stoichiometric feed-combination ceiling, not reaction yield." if aa else
            " That denominator is all CH4 here and half CO2 in the CH4/CO2 map, so the two are not one scale."),
        "Mass-normalized rates are conditional at 50 sccm (0 C, 1 atm), CFP 28.8 mg.", "",
        "| T (C) | tau (s) | C2H2 C-yield % | C2H4 C-yield % | CO C-yield % |"
        + (" AA upper C-yield % |" if aa else " CH4 conversion % |")
        + " C2 stable mg/mgCFP/h | CO mg/mgCFP/h | Sampled Pareto |",
        "|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        rate = r["conditional_mg_product_per_mg_CFP_h"]
        vals = [f"{r['T_C']:g}", f"{r['tau_s']:g}"]
        vals += [f"{100*r[k]:.5f}" for k in ("C2H2_carbon_yield", "C2H4_carbon_yield", "CO_carbon_yield")]
        vals += [f"{100*r['AA_stoichiometric_carbon_upper_bound' if aa else 'CH4_conversion']:.5f}"]
        vals += [f"{rate[k]:.5f}" for k in ("C2_stable_sum", "CO")]
        vals += ["yes" if r in front else "no"]
        lines.append("| " + " | ".join(vals) + " |")
    lines += ["", "![Sampled C2H2 CO Pareto](pareto.svg)", "",
              "Only evaluated points are shown. Nondominance does not establish a global optimum.",
              "Initial-condition and tolerance robustness beyond the recorded gates remains untested."]
    (out / "REPORT.md").write_text("\n".join(lines) + "\n")
    svg = ['<svg xmlns="http://www.w3.org/2000/svg" width="760" height="500" viewBox="0 0 760 500">',
           '<rect width="760" height="500" fill="white"/>',
           '<g font-family="Arial" font-size="13" fill="#172a3a">',
           '<text x="80" y="30" font-size="19">Aramco CJH: evaluated points only</text>',
           '<path d="M80 60V420H700" fill="none" stroke="#172a3a"/>']
    xmax = max(1., max(100*r["C2H2_carbon_yield"] for r in rows)*1.2)
    ymax = 100.
    for i in range(6):
        x, y = 80+620*i/5, 420-360*i/5
        svg += [f'<text x="{x}" y="442" text-anchor="middle">{xmax*i/5:.1f}</text>',
                f'<text x="68" y="{y+4}" text-anchor="end">{ymax*i/5:.0f}</text>']
    for r in rows:
        x = 80 + 620*100*r["C2H2_carbon_yield"]/xmax
        y = 420 - 360*100*r["CO_carbon_yield"]/ymax
        color = "#c54d13" if r in front else "#277da1"
        label = f"{r['T_C']:g} C, {r['tau_s']:g} s"
        svg += [f'<circle cx="{x:.2f}" cy="{y:.2f}" r="5" fill="{color}"><title>{label}</title></circle>']
        if r in front:
            svg += [f'<text x="{x+8:.2f}" y="{y-8:.2f}">{label}</text>']
    svg += ['<text x="360" y="478">C2H2 carbon yield (%)</text>',
            '<text transform="translate(22 290) rotate(-90)">CO carbon yield (%)</text>',
            '<text x="400" y="52">Orange: nondominated among sampled points</text>', '</g></svg>']
    (out / "pareto.svg").write_text("\n".join(svg) + "\n")
    (out / "analysis.json").write_text(json.dumps(dict(points=len(rows),
        pareto=[dict(T_C=r["T_C"], tau_s=r["tau_s"]) for r in front],
        sources=[str(f) for f in a.summaries]), indent=2) + "\n")


if __name__ == "__main__":
    main()
