"""Render a diagnostic archive without changing its raw evidence."""
import argparse
import json
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("archive", type=Path)
    a = ap.parse_args()
    data = a.archive/"data"
    status = json.loads((data/"status.json").read_text())
    gates = json.loads((data/"gates.json").read_text())
    lines = ["# CJH diagnostic comparisons", "",
        "Generated by tools/openmkm_dynamic/summarize_cjh_validation.py.",
        f"Recorded status: {status['status']}; calculation wall time: {status['wall_s']:.6f} s.", "",
        "Species differences are absolute mol/species per mol inlet carbon; conversion differences are absolute fractions.", "",
        "| Comparison | Maximum species difference | CH4 conversion difference |",
        "|---|---|---|"]
    for gate in gates:
        lines.append(f"| {gate['name']} | {gate['max_abs_mol_per_feed_C']:.6e} | {gate['conversion_abs']:.6e} |")
    integrators = sorted(data.glob("*-integrator.json"))
    if integrators:
        lines += ["", "| Recorded integrator | rtol | atol |", "|---|---|---|"]
        for path in integrators:
            settings = json.loads(path.read_text())
            lines.append(f"| {path.stem} | {settings['effective_rtol']:.3e} | {settings['effective_atol']:.3e} |")
    lines += ["", "Only the recorded comparisons are supported. This does not prove initial-state independence, mechanism accuracy or physical reactor feasibility."]
    (a.archive/"REPORT.md").write_text("\n".join(lines)+"\n")


if __name__ == "__main__":
    main()
